# Permalinks
permalink:           pretty

# Setup
title:               dat \'stache
tagline:             welcome!
url:                 http://blog.datstache.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/Datstache
  email:             webmaster+blog@datstache.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Datstache/blog-datstache
google_analytics:
  #id:                

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
